name = "sh1an"
pages_build_output_dir = "docs"
compatibility_date = "2026-06-21"

[[d1_databases]]
binding = "DB"
database_name = "sh1an-songlist"
database_id = "589ea7e6-0951-4b91-b1bf-550bced688e9"
